#!/bin/bash

bspc config border_width         2
bspc config window_gap           12
bspc config top_padding          28
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a inskape desktop=^8 state=floating follow=on
bspc rule -a chromium desktop=II
bspc rule -a Butter desktop=III state=fullscreen

sxhkd &

setxkbmap -layout es

while true;
do
 feh -z --bg-fill .wallpapers/*
 sleep 30s
done &

~/bar.sh &
